name: SuperDiffCheck
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.0"
        rails_appraisal:
          - rails_6_1
        rspec_appraisal:
          - rspec_lt_3_10
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.rails_appraisal }}_${{ matrix.rspec_appraisal }}.gemfile
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Check Ruby
        run: echo ${{ matrix.ruby }}
      - name: Check bundle
        run: bundle list
      - name: Run test
        run: bundle exec rake --trace
